[tool.poetry]
name = "vidyamitra"
version = "0.1.0"
description = "a friendly companion in the journey of learning and knowledge acquisition"
authors = ["Ganesh Rao <ganesh.rao@reva.edu.in>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
django = "^5.0.6"
django-ninja = "^1.3.0"
django-ninja-extra = "^0.21.4"
uvicorn = "^0.30.1"
pyfiglet = "^1.0.2"
termcolor = "^2.4.0"
daphne = "^4.1.2"
langchain = "^0.2.5"
langchain-core = "^0.2.8"
langchain-community = "^0.2.5"
langchain-openai = "^0.1.8"
langchain-google-genai = "^1.0.6"
python-pptx = "^0.6.23"
streamlit = "^1.36.0"
streamlit-book = "^0.7.5"
moodlepy = "^0.24.0"
langchain-pinecone = "^0.1.1"
python-dotenv = "^1.0.1"
mdutils = "^1.6.0"
django-markdownfield = "^0.11.0"
django-cors-headers = "^4.4.0"
docx2txt = "^0.8"
pypdf = "^4.2.0"
python-docx = "^1.1.2"
moodlexport = "^0.0.32"
django-stubs-ext = "^5.0.2"
django-stubs = "^5.0.2"
gunicorn = "^22.0.0"
django-debug-toolbar = "^4.4.6"
django-storages = "^1.14.4"
loguru = "^0.7.2"
psycopg = {extras = ["binary"], version = "^3.2.1"}
pydantic-core = "^2.20.1"
firebase-admin = "^6.5.0"
boto3 = "^1.35.40"
pinecone = "^5.3.1"
jinja2 = "^3.1.4"
cryptography = "^43.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
