# Generated by Django 5.1.3 on 2024-11-22 10:25

import silicon.knowledge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='course name')),
                ('course_code', models.CharField(max_length=512, verbose_name='course code')),
                ('semester', models.IntegerField(verbose_name='semester')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=512, verbose_name='vectorstore namespace')),
                ('name', models.CharField(max_length=512, verbose_name='document name')),
                ('file', models.FileField(blank=True, null=True, upload_to=silicon.knowledge.models.document_dir)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('SYLLABUS', 'Syllabus'), ('OTHER', 'Other')], default='OTHER', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='school name')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
