# Generated by Django 5.1.3 on 2024-11-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirebaseSocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_uid', models.CharField(max_length=50)),
                ('provider', models.CharField(max_length=20)),
            ],
        ),
    ]
