"""Django settings for quiz project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

from silicon._settings.base import *

# Build paths inside the project like this: BASE_DIR / 'subdir'.

INTERNAL_IPS = ("127.0.0.1", "localhost", "reva.syek.in")
SITE_URL = "http://127.0.0.1/"

__VERSION__ = "0.1"
__APP_MODE__ = "local"

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-gzyx(!+@(f0!fvm@75^(u7hn+9t5+_jjo0@fr6of8k8_t4g5g5"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# add django debug_toolbar
INSTALLED_APPS.append("debug_toolbar")
MIDDLEWARE.insert(
    MIDDLEWARE.index("django.middleware.common.CommonMiddleware") + 1,
    "debug_toolbar.middleware.DebugToolbarMiddleware",
)


CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://localhost:3000",  # Next.js frontend
    "http://localhost:5000",
    "http://localhost:8080",  # Frontend development server
    "http://127.0.0.1:3000",  # Next.js frontend
    "http://127.0.0.1:8080",  # Frontend development server
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://localhost:3000",  # Next.js frontend
    "http://localhost:5000",
    "http://localhost:8080",  # Frontend development server
    "http://127.0.0.1:5000",
    "http://127.0.0.1:8000",
    "http://127.0.0.1:3000",  # Next.js frontend
    "http://127.0.0.1:8080",  # Frontend development server
]

# Allow credentials (cookies, authorization headers) in CORS requests
CORS_ALLOW_CREDENTIALS = True

# Application definition


ROOT_URLCONF = "core.urls"


STATIC_ROOT = os.path.join(BASE_DIR, "assets")
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
WSGI_APPLICATION = "silicon.core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# CORS_ORIGIN_ALLOW_ALL = True
