# Generated by Django 5.1.2 on 2026-01-02 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userapikey'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userapikey',
            new_name='user_userap_user_id_1b0ee7_idx',
            old_name='user_userap_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='userapikey',
            new_name='user_userap_user_id_0f9b90_idx',
            old_name='user_userap_user_id_is_active_idx',
        ),
    ]
