# Generated by Django 5.1.3 on 2024-11-19 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0002_initial'),
        ('slides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='presentation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.course'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favorite',
            name='ppt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_presentation', to='slides.presentation'),
        ),
        migrations.AddField(
            model_name='slides',
            name='presentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slides.presentation'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('ppt', 'user'), name='secondary_key', violation_error_message='This presentation is already marked as favorite'),
        ),
    ]
