# Generated by Django 5.1.3 on 2024-11-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_outcome', models.IntegerField(blank=True, null=True)),
                ('question', models.TextField(max_length=1024, verbose_name='Question')),
                ('marks', models.IntegerField(verbose_name='Marks')),
                ('validated', models.BooleanField(default=False)),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], default='M', max_length=1)),
                ('blooms_level', models.IntegerField(choices=[(1, 'Remembering'), (2, 'Understanding'), (3, 'Applying'), (4, 'Analysing'), (5, 'Evaluating'), (6, 'Creating')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='question_images/')),
                ('image_description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
